#!/bin/bash
if [ "$1" == "" ]
then
	echo "Usage: planeinfo <N-number>"
	exit 1
fi


plane=$1

function printtag
{
echo $1: $(grep -i "td data-label=\"$1" /tmp/faaquery.tmp |head -1 | xargs |sed 's/<\/\?[^>]\+>//g' | tr -d "[:cntrl:]")

}

wget -qO /tmp/faaquery.tmp https://registry.faa.gov/AircraftInquiry/Search/NNumberResult?nNumberTxt=${plane:1}

printtag manufacturer
printtag model
printtag "aircraft type"
printtag "engine type"
printtag "mfr year"
printtag "mode s code (base 16 / hex)"
printtag name

rm /tmp/faaquery.tmp
